name: table_calendar
description: Highly customizable, feature-packed calendar widget for Flutter.
version: 3.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  simple_gesture_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
